# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\KULIAH\SEMESTER 3\Algeo\Tubes 2\AlgeoTubes2\main_front.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundLabel = QtWidgets.QLabel(self.centralwidget)
        self.backgroundLabel.setGeometry(QtCore.QRect(-10, -10, 881, 661))
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(320, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        self.titleLabel.setFont(font)
        self.titleLabel.setTextFormat(QtCore.Qt.AutoText)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.searchGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.searchGroup.setGeometry(QtCore.QRect(30, 440, 571, 191))
        self.searchGroup.setObjectName("searchGroup")
        self.formLayoutWidget = QtWidgets.QWidget(self.searchGroup)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 531, 115))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.srcFormLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.srcFormLayout.setContentsMargins(0, 0, 0, 0)
        self.srcFormLayout.setObjectName("srcFormLayout")
        self.sLabel_1 = QtWidgets.QLabel(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sLabel_1.sizePolicy().hasHeightForWidth())
        self.sLabel_1.setSizePolicy(sizePolicy)
        self.sLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.sLabel_1.setObjectName("sLabel_1")
        self.srcFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sLabel_1)
        self.sLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.sLabel_2.setObjectName("sLabel_2")
        self.srcFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sLabel_2)
        self.sLabel_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.sLabel_3.setObjectName("sLabel_3")
        self.srcFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sLabel_3)
        self.topImgInp = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.topImgInp.setObjectName("topImgInp")
        self.srcFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.topImgInp)
        self.matchAlgInp = QtWidgets.QComboBox(self.formLayoutWidget)
        self.matchAlgInp.setObjectName("matchAlgInp")
        self.srcFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.matchAlgInp)
        self.sLabel_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.sLabel_4.setObjectName("sLabel_4")
        self.srcFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sLabel_4)
        self.fastAlgInp = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.fastAlgInp.setEnabled(True)
        self.fastAlgInp.setText("")
        self.fastAlgInp.setObjectName("fastAlgInp")
        self.srcFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fastAlgInp)
        self.imgPathGrid = QtWidgets.QGridLayout()
        self.imgPathGrid.setObjectName("imgPathGrid")
        self.imgPathBtn = QtWidgets.QToolButton(self.formLayoutWidget)
        self.imgPathBtn.setObjectName("imgPathBtn")
        self.imgPathGrid.addWidget(self.imgPathBtn, 0, 1, 1, 1)
        self.imgPathInp = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.imgPathInp.setEnabled(True)
        self.imgPathInp.setObjectName("imgPathInp")
        self.imgPathGrid.addWidget(self.imgPathInp, 0, 0, 1, 1)
        self.srcFormLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.imgPathGrid)
        self.pushButton = QtWidgets.QPushButton(self.searchGroup)
        self.pushButton.setGeometry(QtCore.QRect(20, 150, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.ImInGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.ImInGroup.setGeometry(QtCore.QRect(60, 60, 351, 371))
        self.ImInGroup.setObjectName("ImInGroup")
        self.picInLabel = QtWidgets.QLabel(self.ImInGroup)
        self.picInLabel.setGeometry(QtCore.QRect(10, 20, 331, 341))
        self.picInLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.picInLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.picInLabel.setObjectName("picInLabel")
        self.ImOutGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.ImOutGroup.setGeometry(QtCore.QRect(460, 60, 351, 371))
        self.ImOutGroup.setObjectName("ImOutGroup")
        self.picOutLabel = QtWidgets.QLabel(self.ImOutGroup)
        self.picOutLabel.setGeometry(QtCore.QRect(10, 20, 331, 341))
        self.picOutLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.picOutLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.picOutLabel.setObjectName("picOutLabel")
        self.extGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.extGroup.setGeometry(QtCore.QRect(620, 500, 191, 91))
        self.extGroup.setObjectName("extGroup")
        self.extBtn = QtWidgets.QPushButton(self.extGroup)
        self.extBtn.setGeometry(QtCore.QRect(20, 50, 93, 28))
        self.extBtn.setObjectName("extBtn")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.extGroup)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 161, 21))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.extFormLayout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.extFormLayout.setContentsMargins(0, 0, 0, 0)
        self.extFormLayout.setObjectName("extFormLayout")
        self.extLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.extLabel.setObjectName("extLabel")
        self.extFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.extLabel)
        self.fastAlgExt = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.fastAlgExt.setEnabled(True)
        self.fastAlgExt.setText("")
        self.fastAlgExt.setObjectName("fastAlgExt")
        self.extFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fastAlgExt)
        self.imOutBtnGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.imOutBtnGroup.setGeometry(QtCore.QRect(620, 439, 191, 61))
        self.imOutBtnGroup.setObjectName("imOutBtnGroup")
        self.prevImgBtn = QtWidgets.QPushButton(self.imOutBtnGroup)
        self.prevImgBtn.setGeometry(QtCore.QRect(30, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(14)
        self.prevImgBtn.setFont(font)
        self.prevImgBtn.setObjectName("prevImgBtn")
        self.nextImgBtn = QtWidgets.QPushButton(self.imOutBtnGroup)
        self.nextImgBtn.setGeometry(QtCore.QRect(100, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(14)
        self.nextImgBtn.setFont(font)
        self.nextImgBtn.setObjectName("nextImgBtn")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(720, 600, 93, 28))
        self.exitBtn.setObjectName("exitBtn")
        self.aboutBtn = QtWidgets.QPushButton(self.centralwidget)
        self.aboutBtn.setGeometry(QtCore.QRect(620, 600, 93, 28))
        self.aboutBtn.setObjectName("aboutBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backgroundLabel.setText(_translate("MainWindow", "TextLabel"))
        self.titleLabel.setText(_translate("MainWindow", "Face Recognition App"))
        self.searchGroup.setTitle(_translate("MainWindow", "Search Settings"))
        self.sLabel_1.setText(_translate("MainWindow", "Image In Path"))
        self.sLabel_2.setText(_translate("MainWindow", "Top Image Out"))
        self.sLabel_3.setText(_translate("MainWindow", "Matching Algorithm"))
        self.sLabel_4.setText(_translate("MainWindow", "Fast Algorithm"))
        self.imgPathBtn.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.ImInGroup.setTitle(_translate("MainWindow", "Image In"))
        self.picInLabel.setText(_translate("MainWindow", "TextLabel"))
        self.ImOutGroup.setTitle(_translate("MainWindow", "Image Out"))
        self.picOutLabel.setText(_translate("MainWindow", "TextLabel"))
        self.extGroup.setTitle(_translate("MainWindow", "Extract Database"))
        self.extBtn.setText(_translate("MainWindow", "Extract"))
        self.extLabel.setText(_translate("MainWindow", "Fast Algorithm             "))
        self.imOutBtnGroup.setTitle(_translate("MainWindow", "Image Out Button"))
        self.prevImgBtn.setText(_translate("MainWindow", "<"))
        self.nextImgBtn.setText(_translate("MainWindow", ">"))
        self.exitBtn.setText(_translate("MainWindow", "Exit"))
        self.aboutBtn.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
